#!/usr/bin/env python3
"""Generate the compact UAX #50 orientation table used by the reader.

Input must be the Unicode 16.0.0 VerticalOrientation.txt file. Keeping the
Unicode version and SHA-256 explicit makes a change in the Unicode database a
reviewable reader-layout change rather than an untracked hand-edited range.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


UNICODE_VERSION = "16.0.0"
EXPECTED_SHA256 = "24ac1474554eb55c85ace5c16d551535a8c52cdc2f4c13cf68c3839214339bbe"
PROPERTY_VALUES = {"U": "Upright", "R": "Rotated", "Tu": "TransformedUpright", "Tr": "TransformedRotated"}
LINE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(U|R|Tu|Tr)\b")


def parse(source: Path) -> list[tuple[int, int, str]]:
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"unexpected SHA-256 for {source}: {digest}")
    ranges = []
    for raw in source.read_text(encoding="utf-8").splitlines():
        match = LINE.match(raw)
        if not match:
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2) or match.group(1), 16)
        ranges.append((first, last, match.group(3)))
    if not ranges:
        raise SystemExit("no Vertical_Orientation ranges found")
    return ranges


def render(ranges: list[tuple[int, int, str]]) -> str:
    # R is UAX #50's default value. Omitting its 1,889 explicit source ranges
    # keeps the firmware table compact while retaining U, Tu, and Tr, which
    # need different layout or glyph-fallback handling.
    ranges = [entry for entry in ranges if entry[2] != "R"]
    lines = [
        "// Generated by scripts/generate_vertical_orientation_table.py; do not edit.",
        f"// Source: Unicode {UNICODE_VERSION} VerticalOrientation.txt (SHA-256 {EXPECTED_SHA256}).",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace VerticalTextUtils {",
        "",
        "enum class UaxVerticalOrientation : uint8_t { Upright, Rotated, TransformedUpright, TransformedRotated };",
        "",
        "struct UaxVerticalOrientationRange { uint32_t first; uint32_t last; UaxVerticalOrientation orientation; };",
        "",
        "inline constexpr UaxVerticalOrientationRange UAX_VERTICAL_ORIENTATION_RANGES[] = {",
    ]
    for first, last, value in ranges:
        lines.append(f"    {{0x{first:04X}, 0x{last:04X}, UaxVerticalOrientation::{PROPERTY_VALUES[value]}}},")
    lines.extend([
        "};",
        "",
        "inline UaxVerticalOrientation getUaxVerticalOrientation(const uint32_t codepoint) {",
        "  size_t low = 0;",
        "  size_t high = sizeof(UAX_VERTICAL_ORIENTATION_RANGES) / sizeof(UAX_VERTICAL_ORIENTATION_RANGES[0]);",
        "  while (low < high) {",
        "    const size_t middle = low + (high - low) / 2;",
        "    const auto& range = UAX_VERTICAL_ORIENTATION_RANGES[middle];",
        "    if (codepoint < range.first) high = middle;",
        "    else if (codepoint > range.last) low = middle + 1;",
        "    else return range.orientation;",
        "  }",
        "  return UaxVerticalOrientation::Rotated;  // UAX #50 default value",
        "}",
        "",
        "inline bool isUaxUprightInVertical(const uint32_t codepoint) {",
        "  const auto orientation = getUaxVerticalOrientation(codepoint);",
        "  return orientation == UaxVerticalOrientation::Upright || orientation == UaxVerticalOrientation::TransformedUpright;",
        "}",
        "",
        "}  // namespace VerticalTextUtils",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true", help="fail if output is not the deterministic generated result")
    args = parser.parse_args()
    rendered = render(parse(args.source))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("generated UAX #50 table is stale")
        return
    args.output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
